"""empty message

Revision ID: 6e118954d6f3
Revises: 
Create Date: 2017-10-17 11:47:17.108000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e118954d6f3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=50), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_word', sa.String(length=100), nullable=True),
    sa.Column('product_id', sa.String(length=50), nullable=True),
    sa.Column('product_name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('spec', sa.String(length=255), nullable=True),
    sa.Column('package_num', sa.String(length=10), nullable=True),
    sa.Column('unit', sa.String(length=200), nullable=True),
    sa.Column('price', sa.String(length=10), nullable=True),
    sa.Column('unit_price', sa.String(length=10), nullable=True),
    sa.Column('sales', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('nick', sa.String(length=200), nullable=True),
    sa.Column('product_file_id', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['product_file_id'], ['product_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('product_file')
    # ### end Alembic commands ###
