"""empty message

Revision ID: 63678c49cf13
Revises: 
Create Date: 2017-09-05 16:39:22.334000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63678c49cf13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('create_date', sa.DateTime(timezone=50), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nid', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('view_price', sa.String(length=100), nullable=True),
    sa.Column('item_loc', sa.String(length=200), nullable=True),
    sa.Column('view_sales', sa.String(length=255), nullable=True),
    sa.Column('nick', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('product_file_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_file_id'], ['product_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('product_file')
    # ### end Alembic commands ###
