"""empty message

Revision ID: 9ef1c403923a
Revises: 87072b8fdcfc
Create Date: 2017-10-24 10:36:24.916000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef1c403923a'
down_revision = '87072b8fdcfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like_photo',
    sa.Column('like_photo_id', sa.Integer(), nullable=False),
    sa.Column('photo_liked_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['like_photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['photo_liked_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('like_photo_id', 'photo_liked_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like_photo')
    # ### end Alembic commands ###
