"""empty message

Revision ID: aa89a01a2054
Revises: 9ef1c403923a
Create Date: 2017-10-24 14:35:49.818000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa89a01a2054'
down_revision = '9ef1c403923a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like_album',
    sa.Column('like_album_id', sa.Integer(), nullable=False),
    sa.Column('album_liked_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['album_liked_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['like_album_id'], ['albums.id'], ),
    sa.PrimaryKeyConstraint('like_album_id', 'album_liked_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like_album')
    # ### end Alembic commands ###
